# name: try-catch
# key: try
# --
try {
  $1
} catch (err) {
  $2
}